name: subtask_ui
description: A task tree widget UI
version: 1.0.0
homepage: https://github.com/BLKKKBVSIK/subtask_ui

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^2.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: